#+HTML: <h1 align="center">My Personal Website</h1>
#+HTML: <h2 align="center">Redesigned and Redeveloped (with Nuxt3)</h2>

* Table of Contents :TOC:
  - [[#about][About]]
  - [[#technologies-used][Technologies Used]]
  - [[#download-and-installation][Download and Installation]]
  - [[#licensing][Licensing]]
  - [[#support][Support]]

** About
[[https://img.shields.io/github/commit-activity/m/buraiyen/brianenguyen.com][https://img.shields.io/github/commit-activity/m/buraiyen/brianenguyen.com.svg]]

[[https://gitmoji.dev][https://img.shields.io/badge/gitmoji-%20%F0%9F%98%9C%20%F0%9F%98%8D-FFDD67.svg?style=flat]]

Link to website: [[https://brianenguyen.com][brianenguyen.com]]

My personal website / portfolio that showcases information about me and my
programming work. This website has gone through 2 major overhauls to improve
designs, SEO, speed, and accessibility.

+ [[https://github.com/Buraiyen/BEN-Website][Version 1]]
+ [[https://github.com/Buraiyen/brianenguyen.com-react-archive][Version 2]]

** Technologies Used
+ [[https://nuxt.com/][Nuxt3]]
+ [[https://content.nuxt.com/][Nuxt Content]]
+ [[https://orgmode.org/][org-mode]]
+ [[UnoCSS][UnoCSS]]
+ [[https://icones.js.org/][Icônes]]
  - Box logos
  - Iconoir
  - solar
+ [[https://www.emailjs.com/][EmailJS]]
+ [[https://vitejs.dev/][Vite]]
+ [[https://www.markdownguide.org/][Markdown]]

** Download and Installation
#+begin_src sh
$ git clone https://github.com/Buraiyen/brianenguyen.com.git

...

$ cd brianenguyen.com/
$ npm i
$ npm run dev
#+end_src

** Licensing
All words and original images (files with =BEN_= or =BEN-= prefix)  are licensed
under [[https://creativecommons.org/licenses/by-nc-sa/4.0/][CC BY-NC-SA 4.0]].  Essentially, you can use any of my images and words as
long as you give proper credit to me, do not use it for commercial processes,
and distribute them under the same license

Most unoriginal images (images not owned by me) are taken from [[https://unsplash.com][unsplash.com]]. [[https://unsplash.com/license][See Unsplash's license here]]. Only one photo, =thunder_rosa.webp=, is licensed under [[https://creativecommons.org/licenses/by-sa/2.0/][CC BY-SA 2.0]]

All other directories and files are MIT Licensed (where applicable). Feel free
to inspect my code and reuse them to your liking. See the [[./LICENSE-CODE][LICENSE-CODE]] for more information

** Support
My personal website is a huge passion project of mine, as it is where I document
my life and regularly provide updates to improve it. As I am the only one (as of
now) actively supporting it, I occasionally overlook small details or issues in
my site

If you notice any issues or have questions, please feel free to open an issue in
this repository or reach out to me at =hello@brianenguyen.com=

If you also wish to improve this project, please [[https://github.com/Buraiyen/brianenguyen.com/pulls][submit a pull request.]] All pull
requests will be appreciated, no matter how big or small they are!

If you want to financially support me in contributing to open-source software,
please consider [[https://github.com/sponsors/Buraiyen][sponsoring me on GitHub!]]

No matter what kind of support you give, I will be grateful for taking your time
and consideration to help me out!
