#+title: Why I Blog
#+OPTIONS: toc:nil

* Why I'm Blogging
#+BEGIN_QUOTE
11 Feb, 2022 · 1 min
#+END_QUOTE

** The Purpose
Recently, I've observed that many online programming tutorials and tech
discussions are presented through blogs. As a result, I have decided to start
writing my own blog. The primary objectives of my blog are to share my knowledge
and experiences, as well as to enhance my writing skills. Additionally, through
writing blog posts, I can develop a better understanding of programming concepts
and gain a deeper understanding of myself.

** What can you expect?
I plan on providing my blogs with the following:

- *programming* - these will be cover a wide range of topics, not just limited to
  my field in web development
- *my life*  - I enjoy documenting my life to preserve my memories and share my
  experiences with others. This will give you a better understanding of me
  beyond my passion for programming.

** What makes my blogs different?
What I don't like about many online blogs is that they waste your time. Have you
ever tried to search for a recipe for your favorite dish online? If you haven't,
I encourage you do so that you can see my point. Most likely when you find a
recipe, the author presents useless information in their blog, such as the
history of the dish, how they discovered it, why they like it, and other boring
info.

Then, at the END of the blog, that's when the author lists out the ingredients
and steps on how to make the dish. Their goal is to boost their page's SEO,
prioritizing search engine visibility over user convenience and efficiency.

*I value your time.* In these blogs, I focus on providing you with quality
knowledge and insights while respecting your time.

Additionally, I aim to focus on unique topics. These blogs won't be your
typical /React vs. Vue/, or /What's the Difference Between Aperture, ISO, and Shutter Speed?/.
Instead, I will delve into lesser-explored topics that go beyond the mainstream.
