#+title: Blogging With Org Mode

#+options: toc:nil
* Writing My Blogs with Org Mode
#+BEGIN_QUOTE
16 Feb, 2022 · 5 min
#+END_QUOTE

I used JSX to write my blogs, which helped me get the job done, but it was a
huge hassle. I had to worry about JSX syntax, bugs, CSS classes, etc. These
problems distracted me from the actual content creation.  After my blog files
were done, they ended up being a messy compilation filled with JSX syntax that
distracts the user from the actual text content.  This honestly demotivated me
from writing blogs

I knew I had to find a solution to this problem. Instead of using JSX, I had to
turn to my favorite markup language to do the work: Org Mode

** What is Org Mode?
Org Mode (also /org-mode/) is a type of markup language used in Emacs. I love
org-mode because its very versatile in what it can do. I use to to take notes,
write documents, make an agenda, and develop websites. It's my preferred markup
language over Markdown (which I will explain more in a future blog)

** Setup / Methods
Since there isn't really a dedicated package that converts org-mode to JSX, I had to resort to writing my documents in org-mode first, then exporting them to Markdown

There are many packages that can help parse org-files into JSX, like =react-markdown= and =markdown-to-jsx=. Since I am using the Vite engine to build
this React app, I use the [[https://github.com/geekris1/vite-plugin-react-markdown][vite-plugin-react-markdown]] package for this website

Once this package is installed, I had to configure my =vite.config.js= file to
utilize the package and allow the app to include Markdown files

#+begin_src js
// vite.config.js
import { defineConfig } from 'vite';
import Markdown from 'vite-plugin-react-markdown';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [
    Markdown(),
    react({
      include: [/\.tsx$/, /\.md$/], // <-- add .md
    }),
  ],
});
#+end_src

For my blog posts, I set up a component called =BlogPostView= that retrieves a
Markdown file and parses it to JSX

#+begin_src js
import React, { useEffect, useState } from 'react';
import './BlogPostView.css';

const BlogPostView = ({ markdownFile, title }) => {
  const [content, setContent] = useState(null);

  useEffect(() => {
    import(`../../../pages/blog/${markdownFile}.md`)
      .then((res) => {
        setContent(res.default);
      })
      .catch((err) => {
        console.log(`Failed to import Markdown: ${err}`);
      });
  }, [markdownFile]);

  return (
    {content && <>{content}</>}
  );
};

export default BlogPostView;
#+end_src

For my method, I set up a state called =content=. Once the component loads, it retrieves the Markdown file from the prop that was passed in. Once it is able to retrieve the data, then the component sets the state of that data to =content=

#+begin_src js
const BlogPostView = ({ markdownFile, title }) => {
  const [content, setContent] = useState(null);

  useEffect(() => {
    import(`../../../pages/blog/${markdownFile}.md`)
      .then((res) => {
        setContent(res.default);
      })
      .catch((err) => {
        console.log(`Failed to import Markdown: ${err}`);
      });
  }, [markdownFile]);

...
#+end_src
** Problems and Solutions
*** The =import= statement
*** Images
