#+title: Hello Nebraska!
#+options: toc:nil

* Hello Nebraska!
#+begin_quote
TBA date and min
#+end_quote

I am excited to share that I have *moved to Nebraska!*

Why am I doing so? Early this year, I found a web developer job posting from a
company called *IdeaBank Marketing*. I was intrigued by the services they offer
and the company culture, so I decided to reach out to one of the owners. I had a
couple of interviews with them, and I made it to the final stage of the
interview process. Eventually, they reached out to me if I would like to visit
Nebraska. I traveled there at the end of May to visit their company and meet
their coworkers.

A few days later, I received an offer from IdeaBank and I accepted it! I will
begin my position starting on the first week of July.

** Why move to Nebraska?
I'm honestly stressed living in California, where the life here is more hectic.
Factors include high cost of living, congested traffic, and job competition.
I've always wanted to live in an area where life is less stressful. When I
visited Nebraska, I felt like I was at peace. Moving away from the big city life
was a culture shock to me, but I quickly got used to it.

In addition, I want to experience living on my own. I've always been dependent of
others for my living situation, but I need an opportunity to know what it's like
to be independent.
