#+OPTIONS: toc:nil

* My First Maternity Photography Session
#+BEGIN_QUOTE
11 Feb, 2022 · 1 min
#+END_QUOTE

As a photographer, I had the privilege of documenting my friends who are
expecting their first baby. This is also my very first maternity photoshoot, and
it was a memorable and enjoyable experience.

** Setting the Scene
Sunset photography is my specialty. The combination of the sun's warm glow and the crashing waves creates a perfect setting, especially

I wanted to make sure that my shots felt magical, so I had to utilize the sun in
the background for most of my shots

** Photos
I ensured that the couple is having a delightful experience at the beach, and
that their companionship underneath the scorching sun is surreal to them. To
achieve this, I positioned them in various poses and guided them through actions

In addition, I wanted to utilize the sun's warm aura for my color grading. I
aimed for using only warm colors for my style rather than usual style of both
warm and cool colors. This is a new style that I wanted to try, and it turned
out well

- Walking alongside the beach
- The husband holding the wife's stomach

In addition to capturing beautiful moments of the couple, it was equally
important to include photos of just the wife in the photos. As the main star of
the session, her presence and connection with the baby are significant and
deserved to be highlighted

** Color Grading

** Additional Photos
