#+options: toc:nil

* Visiting Universal Studios Hollywood after 10+ Years

#+begin_quote
TBA · TBA
#+end_quote

I recently visited Universal Studios Hollywood on the 18th and 21st of June.
This is the first time I have been there after more than 10 years. While some
aspects remained unchanged, there were numerous alterations, for better or for
worse. This blog documents my experiences throughout my time at Universal
Studios Hollywood, including my personal opinions on how much the park
transformed the past decade.  Please note that this blog contains many of my
subjective opinions, and while you are welcome to agree or disagree, I kindly
request that you respect my opinions.

** tl;dr
Among all of my visits at Universal Studios Hollywood, this recent experience
stands out as my favorite by far. Despite the large crowds on Father's Day, I
was fortunate enough to experiences nearly everything that the park has to
offer. While I did encounter some negatives, the pros ultimately outweighed the
cons.

*** Pros
+ Everything in Super Nintendo Land
+ New Simpsons environment
+ The Wizarding World of Harry Potter
+ Waterworld
+ Secret Life of Pets ride
+ Pink's Hot Dogs
+ Transformers 3D

*** Indifferent
+ Giant pink frosted sprinkled donut
+ Butter beer
+ Despicable Me ride
+ The Mummy ride

*** Cons
+ Breakfast
+ Studio Tour
+ Dreamworks Theater

** One of the worst breakfasts I had
To kickstart the day, we went to a France-themed restaurant for some breakfast.
I got a vegetarian "bánh mì" and my girlfriend got crepes. As I picked the bánh
mì from the cold stand, my girlfriend warned me that I shouldn't buy Asian food
at non-Asian restaurants because of the authenticity and quality of the food. I
still wanted to try it out and see if I would like it.

Unfortunately, the bánh mì was terrible. There was no protein in it, not even
tofu, and only consited of vegetables. Its tastes had no resemblance to the
authentic flavors of traditional bánh mì, leaving me confused as to why this
"bánh mì" bears that name. In addition, my girlfriend had one of the strawberry
crepes.  Even though it's called /STRAWBERRY/ crepe, there were barely any
strawberries in it.  I don't understand why this restaurant at a highly-established
theme park can offer such low quality food.

[insert picture of crepe]

** Studio Tour
As a kid, the first attraction that I always go to when I enter Universal
Studios is the studio tour. This attraction is a great introduction to park
visitors, allowing them to explore studio backlots and witness how films are
shot. We did the same thing again for this visit.

While the tour didn't change much, this experience wasn't as good as back when I
was a kid. The tour used to have exciting stops, such as Mini Skull Island, Fast
& Furious' Carnage and Carma, The Mummy, and Jaws. This time, none of those
attractions weren't present. The only two that were there were King Kong 3D and
Fast & Furious 3D. The latter was the first time that I've experienced this, and
I believe it replace The Mummy studio tour experience.  I thought this
attraction was ok, but overall, this studio tour didn't provide the same
excitement I had as a kid.

** The Simpsons Ride, Giant Pink Frost Sprinkled Donut
Next, we went to The Simpsons ride. I'm still sad that this replaced the Back to
the Future ride, which I only to ride it once before its replacement.
Nevertheless, I still greatly enjoy The Simpsons ride, and fortunately, nothing
changed about it since last time I've been there.

When The Simpsons ride was initially introduced, the surrounding scenery was
still undergoing construction. At that time, the only available spot was the
Kwik-E-Mart, offering Simpsons-themed souvenirs. However, the area has now been
transformed to include buildings and references from The Simpsons. Some of these
structures serve as guest facilities, such as Moe's Tavern (a restaurant and
bar) and Luigi's Pizza.

Arguably the most popular food item that's being sold in The Simpsons area is
the large Lard Lad Donuts. These donuts are colossal, approximately the size of
an average adult's head. There's dedicated store solely for selling these
donuts, and there is always a long line that forms outside. We decided to get
the giant pink frosted sprinkled donut since that is the most common donut
featured on the show.

The donut tastes good, but it's nothing special. It's just like every other
donut. Obviously the only selling point for these donuts is their tremendous
size, but it was still a good experience to try it out.

[insert picture here with mmm... donuts]

** Waterworld
When it comes to intense, fast-paced, action-packed live shows, nothing comes
close to Waterworld. Inspired by the blockbuster film, Waterworld pushes the
boundaries of visitors' expectations, offering a spectacle that is rarely seen
in theme parks. It features death-defying stunts to exhilarating jet-ski
battles. Watching this show now still made me feel like the first time I watched
it

Waterworld is my all-time favorite live action show at a theme park, and I'm
glad that it's still at Universal Studios. Nothing about it changed.

** The Wizarding World of Harry Potter
I've never consumed a single Harry Potter media, so please excuse me on my lack
of knowledge of Harry Potter

Before the Wizarding World of Harry Potter was here, there used to be Shrek 4D
and a mini water park for children that was SpongeBob themed. Now that this area
has been established, the park feels so much bigger. I'm not a fan of Harry
Potter (nothing against it, I've just never had a chance to read the books or
watch the movies), but I must admit that the area was very immersive. I felt
like that I was inside of a medieval fantasy land. The giant castle that houses
/Harry Potter and the Forbidden Journey/ ride was colossal. It reminded me of the
castles found in the game /Dark Souls/.

One of my friends recommended me to try the butter beer, and the butter beer
stand was the first thing I saw as I walked through the towering gates. The
butter beer is just root beer float. There are two variations of the butter
beer: cold and frozen. I had the frozen one and it's quite enjoyable. It's sweet
and a good beverage during a hot weather; however, $10 for one cup is
excessively high.

The best attraction in this area was definitely /Harry Potter and the Forbidden Journey/. This is one of the most unique rides I've ever seen. Unlike traditional
roller coasters, this ride has you suspended in a seat and you glide through many
obstacles and screens. It's honestly hard to describe how amazing this ride is and
how it works. Just know that it was a remarkable and unparalleled experience

** Illumination
*** Despicable Me Ride
The Despicable Me ride replaced the Terminator ride. As a huge fan of the
Terminator ride and the movie series, I was sad that this was gone.  The
Despicable Me ride is a 3D motion simulator that takes you through the story of
riders being converted into minions and having to go through the minion training
and obstacle courses.  The ride itself was alright. Nothing was intense about it
and it was obviously targeted towards families and children.

From a business standpoint, replacing Terminator with Despicable Me was
the right call. The Illumination area was packed with children and it had way
more activity than Terminator ever did

*** Secret Life of Pets Ride
This fun ride offers a unique experience in which you would ride in a car shaped
like a cardboard box. The first thing riders would go through is "converting" them
into pets through a camera that tracks the riders' facial features (this facial
data is automatically deleted, per Universal Studios' privacy policy). The ride
then goes through the wacky adventures that pets go through while their owners are away

This was definitely a fun and unique ride for all ages.


** Dreamworks Theater
This attraction replaced Shrek 4D. For this attraction, the theme was Kung Fu Panda,
so I got to experience this. Unfortunately, this is way worse than Shrek 4D. In
Shrek 4D, it was presented like an interactive movie format with special
effects, like water and bugs crawling underneath your feet.

As I experienced the Dreamworks Theater, I noticed a very similar pattern with
the rides I've been on. Most of them follow the same format of a 3D simulation
where the riders follow the characters on a journey through excitement and danger.
This makes the rides very predictable

** Lunch
We've got lunch at Pink's Hot Dogs since I wanted to give my girlfriend the
experience of a renowned, local, and famous hot dog restaurant

The hot dogs were tasty. The chili inside my hot dog unfortunately was either
too hot or too heavy for the bun, and the bun broke off. I had to eat the
rest of the hot dog with a fork.

** Super Nintendo Land
Super Nintendo Land opened in early 2023, and I was fortunate that I got to
experience it. As we approached the entrance, we had to go through the green
pipe to enter the area. Walking through the green pipe had rainbow LED lights
and played the descending-pipe sound that we know from the video games. As we
exited the pipe, we've entered Princess Peach's castle, where the environment
feels heavily inspired from the same castle from Super Mario 64

The moment we've exited Peach's castle, I was immediately star-struck. I felt
like I was fully immersed inside of a Mario World. The area featured iconic
grassy hills, pirahna plants emerging from green pipes, rotating coins, brick
and powerup blocks, goombas, koopas, Yoshi, and more. The area has so much
attention to detail everywhere you look, and those who look closely can spot
hard-to-notice things.

*** Mario Kart: Bowser's Challenge
This ride is the main attraction of the area. The wait was 90 minutes, the
longest I had to wait for an attraction that day, but I hoped that it would be
worth it.  The line crosses through Bowser's Castle, and just like any other
area in Super Mario World, there is so much attention to detail. There are
trophies, a giant statue of Bowser, a Bob-Omb factory, and more. My favorite
one are the bookshelves whose book titles are refererences to the Mario
Kart games. Such includes "The History of Moo Moo Farm" and one that
shows shortcuts in several Mario Kart maps

The ride itself, words cannot describe how amazed I am from this ride.
The ride has 4 riders in one car. Each rider can control the direction of
the kart. They would also wear interactive glasses that allows them to
see Team Mario and Team Bowser. They would then use the buttons
on their steering wheel to shoot shells at Team Bowser. Through the
ride, we went through iconic Mario Kart tracks such as Bowser's Castle
and Rainbow Road

Out of all the rides I've been on at Universal Studios, this is definitely
the best one.

** Lower Lot
*** Jurassic World
The Jurassic World ride is essentially the same as the Jurrasic Park ride.
The only difference is that the environments are updated to have
a more modern / futuristic feel

*** Transformers 3D
I /most likely/ have been on the Transformers ride before as a kid. Either way, it
was a very fun and fast-paced 3D ride that has riders transporting the All-Spark
to a safe location while the Autobots and Decepticons are battling each other

*** The Mummy
This is the first time I've been on The Mummy since I've always been
scared of roller coasters as a kid. The ride features cinematics,
ride in the dark, and reverse tracks. It wasn't too intense, but it's
a nice experience

** Conclusion
I had a blast with my experiences at Universal Studios. Super Nintendo Land
was once of the best places I've been in a theme park. Even though there were
some negatives at my visit, the pros outweighed the cons. Universal Studios
is a must-visit destination for California residents or tourists
