#+options: toc:nil

* Visiting Universal Studios Hollywood after 10+ Years

#+begin_quote
TBA · TBA
#+end_quote

I recently visited Universal Studios Hollywood on the 18th of June. This is the
first time I have been there after more than 10 years. Some things have stayed
the same, many things have changed, for better or for worse. This blog documents
my experiences throughout my time at Universal Studios Hollywood. Please note
that this blog has a lot of my personal opinions, and you are free to (dis)agree
as long as you respect my opinions.

** One of the worst breakfasts I had
To start off the day, I went to a France-themed restaurant for some breakfast. I
got a "bánh mì" and my girlfriend got crepes. As I picked the bánh mì, my
girlfriend warned me that I shouldn't buy Asian food at non-Asian restaurants
because of the authenticity and quality of the food. I still wanted to try it out and see if I would like it

However, to my extreme dismay, it was terrible. There was no protein in it, only vegetables. It didn't even taste like bánh mì

** Studio Tour
As a kid, the first attraction that I always go to when I enter Universal Studios is
the studio tour. This attraction is a great introduction to park visitors for them to
view studio backlots, how movies shoot their films, etc.

The tour didn't change much; however, this experience was worst now than back
when I was a kid. The tour used to have exciting stops, such as Mini Skull
Island, Fast & Furious's Carnage and Carma, The Mummy, and Jaws. This time,
none of those attractions were present. The only two that were there were
King Kong 3D and Fast & Furious 3D. The latter was the first time that I've
experienced this, and I believe it replace The Mummy studio tour experience.
I thought this attraction was ok

Overall, my experience with the Studio Tour was better back then than now

** The Simpsons Ride, Giant Pink Frost Sprinkled Donut
Next, we went to The Simpsons ride. I'm still sad that this replaced the Back to
the Future ride as I only ever got to ride it once before it was replaced.
Nevertheless, I still greatly enjoy The Simpsons ride.  Nothing changed about it
since last time I've been there

Back when The Simpsons ride was established, the scenery around it was still
under construction. The only place that was available at the time was the
Kwik-E-Mart, which has Simpsons-related souvenirs. Now, this area features
buildings and references from The Simpsons. Some of them serve areas for guest
needs, like Moe's Tavern (restaurant and bar) and Luigi's Pizza.

Arguably the most popular food item that 's being sold in The Simpsons area is
the large Lard Lad Donuts. These donuts are approximately the size of an average
adult's head. There's one store that is dedicated to only selling the donuts,
and there is always a long line that forms outside. We decided to get the giant
pink frosted sprinkled donut, since that is the most common donut featured on
the show.

The donut tastes good, but it's nothing special. It's just like every other
donut. Obviously the only selling point for these donuts is their tremendous
size, but it was still a good experience

[insert picture here with mmm... donuts]

** Waterworld
When it comes to intense, fast-paced, action-packed live-shows, nothing comes
close to Waterworld. Inspired by the blockbuster film, Waterworld pushes the
boundaries of visitors' expectations, offering a spectacle that is rarely seen
in theme parks. It features death-defying stunts to exhilarating jet-ski
battles. Watching this show now still made me feel like the first time I watched
it

Waterworld is my all-time favorite live-action show at a theme park, and I'm
glad that it's still at Universal Studios. Nothing about it changed.

** The Wizarding World of Harry Potter
I've never consumed a single Harry Potter media, so please excuse me on my lack
of knowledge of Harry Potter

My friend recommended me to try the butter beer, and the butter beer stand was
the first thing I saw as I walked through the towering gates. The price was around
$10



** Despicable Me Ride

** Dreamworks Theater

** Super Nintendo Land

** Lower Lot
