#+options: toc:nil

* Visiting Universal Studios Hollywood after 10+ Years

#+begin_quote
TBA · TBA
#+end_quote

I recently visited Universal Studios Hollywood on the 18th of June. This is the
first time I have been there after more than 10 years. Some things have stayed
the same, many things have changed, for better or for worse. This blog documents
my experiences throughout my time at Universal Studios Hollywood. Please note
that this blog has a lot of my personal opinions, and you are free to (dis)agree
as long as you respect my opinions.

** One of the worst breakfasts I had
To start off the day, I went to a France-themed restaurant for some breakfast. I
got a "bánh mì" and my girlfriend got crepes. As I picked the bánh mì, my
girlfriend warned me that I shouldn't buy Asian food at non-Asian restaurants
because of the authenticity and quality of the food. I still wanted to try it out and see if I would like it

However, to my extreme dismay, it was terrible. There was no protein in it, only vegetables. It didn't even taste like bánh mì

** Studio Tour
As a kid, the first attraction that I always go to when I enter Universal Studios is
the studio tour. This attraction is a great introduction to park visitors for them to
view studio backlots, how movies shoot their films, etc.

The tour didn't change much; however, this experience was worst now than back
when I was a kid. The tour used to have exciting stops, such as Mini Skull
Island, Fast & Furious's Carnage and Carma, The Mummy, and Jaws. This time,
none of those attractions were present. The only two that were there were
King Kong 3D and Fast & Furious 3D. The latter was the first time that I've
experienced this, and I believe it replace The Mummy studio tour experience.
I thought this attraction was ok

Overall, my experience with the Studio Tour was better back then than now

** The Wizarding World of Harry Potter
I've never consumed a single Harry Potter media, so please excuse me on my lack
of knowledge of Harry Potter

My friend recommended me to try the butter beer

** The Simpsons Ride, Giant Pink Frost Sprinkled Donut

** Waterworld

** Despicable Me Ride

** Dreamworks Theater

** Super Nintendo Land

** Lower Lot
