#+options: toc:nil

* Visiting Universal Studios Hollywood after 10+ Years

#+begin_quote
TBA · TBA
#+end_quote

I recently visited Universal Studios Hollywood on the 18th and 21st of June.
This is the first time I have been there after more than 10 years. Some things
have stayed the same, many things have changed, for better or for worse. This
blog documents my experiences throughout my time at Universal Studios Hollywood.
Please note that this blog has a lot of my personal opinions, and you are free
to (dis)agree as long as you respect my opinions.

** tl;dr
Overall, this is my favorite experience in Universal Studios Hollywood out of
all the times I've been there as a kid. I was fortunate enough to experience
almost everything in one day, despite the heavy crowds in Father's Day. Although
a noticed quite a bit negatives in my experiences, the pros ultimately
outweighed the negatives

** One of the worst breakfasts I had
To start off the day, I went to a France-themed restaurant for some breakfast. I
got a "bánh mì" and my girlfriend got crepes. As I picked the bánh mì, my
girlfriend warned me that I shouldn't buy Asian food at non-Asian restaurants
because of the authenticity and quality of the food. I still wanted to try it out and see if I would like it

However, to my extreme dismay, it was terrible. There was no protein in it, only vegetables. It didn't even taste like traditional bánh mì. I have no idea why they
even called it that. In addition, my girlfriend had one of the strawberry crepes.
Even though it's called /STRAWBERRY/ crepe, there were barely any strawberries in it.
I don't understand why this restaurant offers low-quality food

[insert picture of crepe]

** Studio Tour
As a kid, the first attraction that I always go to when I enter Universal
Studios is the studio tour. This attraction is a great introduction to park
visitors for them to view studio backlots, how movies shoot their films, etc.

The tour didn't change much; however, this experience wasn't as good as back
when I was a kid. The tour used to have exciting stops, such as Mini Skull
Island, Fast & Furious' Carnage and Carma, The Mummy, and Jaws. This time, none
of those attractions were present. The only two that were there were King Kong
3D and Fast & Furious 3D. The latter was the first time that I've experienced
this, and I believe it replace The Mummy studio tour experience.  I thought this
attraction was ok

** The Simpsons Ride, Giant Pink Frost Sprinkled Donut
Next, we went to The Simpsons ride. I'm still sad that this replaced the Back to
the Future ride as I only ever got to ride it once before it was replaced.
Nevertheless, I still greatly enjoy The Simpsons ride.  Nothing changed about it
since last time I've been there

Back when The Simpsons ride was established, the scenery around it was still
under construction. The only place that was available at the time was the
Kwik-E-Mart, which has Simpsons-related souvenirs. Now, this area features
buildings and references from The Simpsons. Some of them serve areas for guest
needs, like Moe's Tavern (restaurant and bar) and Luigi's Pizza.

Arguably the most popular food item that 's being sold in The Simpsons area is
the large Lard Lad Donuts. These donuts are approximately the size of an average
adult's head. There's one store that is dedicated to only selling the donuts,
and there is always a long line that forms outside. We decided to get the giant
pink frosted sprinkled donut, since that is the most common donut featured on
the show.

The donut tastes good, but it's nothing special. It's just like every other
donut. Obviously the only selling point for these donuts is their tremendous
size, but it was still a good experience

[insert picture here with mmm... donuts]

** Waterworld
When it comes to intense, fast-paced, action-packed live-shows, nothing comes
close to Waterworld. Inspired by the blockbuster film, Waterworld pushes the
boundaries of visitors' expectations, offering a spectacle that is rarely seen
in theme parks. It features death-defying stunts to exhilarating jet-ski
battles. Watching this show now still made me feel like the first time I watched
it

Waterworld is my all-time favorite live-action show at a theme park, and I'm
glad that it's still at Universal Studios. Nothing about it changed.

** The Wizarding World of Harry Potter
I've never consumed a single Harry Potter media, so please excuse me on my lack
of knowledge of Harry Potter

My friend recommended me to try the butter beer, and the butter beer stand was
the first thing I saw as I walked through the towering gates. The butter beer is
just root beer float. I decided to try it out. There are two versions of the
butter beer: cold and frozen. I had the frozen one, and it's not too bad. It's
sweet and a good beverage during a hot weather; however, $10 for it is asking
WAY too much

** Despicable Me Ride
The Despicable Me ride replaced the Terminator ride. As a huge fan of the ride
and the movie series, I was sad that this was gone.  The Despicable Me ride is a
3D motion simulator that takes you through the story of riders being converted
into minions and having to go through the minion training and obstacle courses.
The ride itself was alright. Nothing was intense about it and it was obviously
targeted towards families and children.

From a business standpoint, replacing Terminator with Despicable Me was
the right call. The Illumination area was packed with children and it had way
more activity than Terminator ever did

** Dreamworks Theater

** Super Nintendo Land

** Lower Lot
